name: AuthMe
author: whoami
description: AuthMe prevents people, which aren't logged in, from doing stuff like placing blocks, moving, typing commands or seeing the inventory of the current player.
main: uk.org.whoami.authme.AuthMe
version: 2.0
commands:
    register:
        description: Register an account
        usage: /register password
    login:
        description: Login into a account
        usage: /login password
    changepassword:
        description: Change password of a account
        usage: /changepassword oldPassword newPassword
    logout:
        description: Logout
        usage: /logout
    unregister:
        description: unregister your account
        usage: /unregister password
    authme:
        description: AuthMe op commands
        usage: '/authme reload|register playername password|changepassword playername password|unregister playername'
permissions:
    authme.*:
        description: Gives access to all authme commands
        children:
            authme.register: true
            authme.login: true
            authme.changepassword: true
            authme.logout: true
            authme.unregister: true
    authme.admin.*:
         description: Gives access to all authme admin commands
         children:
             authme.admin.reload: true
             authme.admin.register: true
             authme.admin.changepassword: true
             authme.admin.unregister: true
    authme.register:
        description: Register an account
        default: true
    authme.login:
        description: Login into a account
        default: true
    authme.changepassword:
        description: Change password of a account
        default: true
    authme.logout:
        description: Logout
        default: true
    authme.unregister:
        description: unregister your account
        default: true
    authme.admin.reload:
        description: AuthMe reload commands
        default: op
    authme.admin.register:
        description: AuthMe register command
        default: op
    authme.admin.changepassword:
        description: AuthMe changepassword command
        default: op
    authme.admin.unregister:
        description: AuthMe unregister command
        default: op